guests = ['Mary', 'Carrie', 'Matt']
print("Dear " + guests[0] + ", you're invited to dinner.")
print("Dear " + guests[1] + ", you're invited to dinner.")
print("Dear " + guests[2] + ", you're invited to dinner.")
print(guests[1] + " can't make it.")
guests[1] = 'Adam'
print("Dear " + guests[0] + ", you're invited to dinner.")
print("Dear " + guests[1] + ", you're invited to dinner.")
print("Dear " + guests[2] + ", you're invited to dinner.")
print("I found a bigger dinner table, so let's invite more guests.")
guests.insert(0, 'John')
guests.insert(2, 'Elizabeth')
guests.append('Fred')
print("Dear " + guests[0] + ", you're invited to dinner.")
print("Dear " + guests[1] + ", you're invited to dinner.")
print("Dear " + guests[2] + ", you're invited to dinner.")
print("Dear " + guests[3] + ", you're invited to dinner.")
print("Dear " + guests[4] + ", you're invited to dinner.")
print("Dear " + guests[5] + ", you're invited to dinner.")
print("The table won't arrive in time. I can only invite two guests.")
popped_guest = guests.pop()
print("I'm sorry I can't invite you to dinner, " + popped_guest + ".")
popped_guest = guests.pop()
print("I'm sorry I can't invite you to dinner, " + popped_guest + ".")
popped_guest = guests.pop()
print("I'm sorry I can't invite you to dinner, " + popped_guest + ".")
popped_guest = guests.pop()
print("I'm sorry I can't invite you to dinner, " + popped_guest + ".")
print(guests[0] + ", you're still invited.")
print(guests[1] + ", you're still invited.")
del guests[1]
del guests[0]
print(guests)
